### ISSUE TITLE
Mismatch with Ulaby 2014

### ISSUE THREAD

**Issue by PMarzahn** [PMarzahn/sense#1]
Oh92 (Plot1):
http://mrs.eecs.umich.edu/codes/Module10_5/Module10_5.html

Dubois95(Plot2)
http://mrs.eecs.umich.edu/codes/Module10_7/Module10_7.html

**Comment by BenMGeo** [comment]
There is no mismatch within the code, but for the plots (Ulaby code does not produce the same values as shown in plot)!
![screenshot at 2017-08-01 16 02 16](https://user-images.githubusercontent.com/14977178/28829041-dd2dca84-76d2-11e7-8e54-6ac8125800dc.png)

Java Script differs to matlabcode:
http://mrs.eecs.umich.edu/codes/Module10_5/plotLibrary.js

**Comment by BenMGeo** [comment]
So far for Oh92, Dubois95 still to be checked!

**Comment by BenMGeo** [comment]
There was a unit error for ks in dubois95!

Should be solved now.
